Makefile, README.md, patch/attiny85.yaml, patch/common/ac.yaml, patch/common/ac/acsr.yaml, patch/svdpatch.py
This integrates YAML based SVD patching with [`svdpatch.py`](https://github.com/stm32-rs/stm32-rs/blob/master/scripts/svdpatch.py) of [stm32](https://github.com/stm32-rs/stm32-rs). Since many atdf files already have definitions for `enumeratedValues`, this also supports replacing existing definitions as a first step (Later on, advanced modification might be an option).
I included an example patch for the attiny85 as a reference.
=> Add svd patching support with svdpatch.py

patch/atmega1280.yaml
As far as I can tell the pll does not exist for the atmega1280, but the rest seems to apply.
=> atmega1280: Add remaining common patches

patch/atmega328p.yaml
Added missing patches for atmega328p by copying the commons from atmega32u4, omitting PLL because the 328p lacks that feature
=> Added missing patches for atmega328p

patch/atmega1280.yaml, patch/atmega328p.yaml, patch/atmega32u4.yaml, patch/atmega64.yaml, patch/common/adc.yaml
Patch needed for ADC implementation
currently only `atmega328p`
[avr-hal/11](https://github.com/Rahix/avr-hal/issues/11)
=> Add patches for ADC peripherals

macros/Cargo.toml, macros/src/lib.rs, src/lib.rs
This is the last major thing needed for crates.io release.  Add a `#[entry]` macro which hides the actual entry implementation.  This will allow us to later transparently switch away from the avr-libc runtime to something completely custom.
The macro is similar to the one from [`cortex-m-rt`](https://github.com/rust-embedded/cortex-m-rt/blob/98e4c3c8597f1dfa52d55616c7ce7cf90682d95b/macros/src/lib.rs#L18).  However, the [automagic static mut vodoo](https://docs.rs/cortex-m-rt/0.6.12/cortex_m_rt/attr.entry.html) has not yet been added here.
Fixes #15.
=> Add an #[entry] macro

src/asm.rs, src/lib.rs
Add a new module containing wrapper functions for various assembly instructions.  These functions are marked inline(always) to ensure they will always just generate the single instruction as expected.
=> Add asm module for assembly instructions

src/interrupt.rs
To bring this crate more in line with cortex-m, mark interrupt::enable() as unsafe.  This also fixes a soundness issue: When the function is safe, one could call it inside a critical section in entirely safe rust.  This is problematic because lot's of code in critical sections relies on the fact that interrupts are disabled and it thus can safely perform non-atomic operations without anything interrupting it.
=> Make interrupt::enable() unsafe

src/interrupt.rs
This one is embarrasing (and I have absolutely no clue how it slipped in!): The SREG is at IO address 0x3F, not 0x35.  Fix interrupt::free() to read the correct register to make it work as advertised.
=> Fix interrupt::free() reading wrong address

Cargo.toml, Makefile, README.md, patch/atmega168.yaml, src/devices/mod.rs, src/lib.rs, vendor/atmega168.atdf
Pull in the ATDF file from Microchip and add all the necessary plumbing
around the code-base to make it compile.
Signed-off-by: Karl Thorén <karl.h.thoren@gmail.com>
=> Add basic support for ATmega168

macros/src/lib.rs
There [have been](https://github.com/Rahix/avr-hal/issues/29) a [couple times](https://github.com/Rahix/avr-hal/issues/39) where an incorrectly set target file has caused errors that don't immediately point to the problem. Instead, we should show an error immediately telling the user that the wrong architecture has been selected.
=> Error if the wrong architecture is being used

Cargo.toml, src/asm.rs, src/interrupt.rs
Make sure that we'll never emit AVR assembly on non-AVR targets.  Instead of failing the build, fail at runtime, to allow a potential application testsuite to run even if those functions somehow get linked in.
Follow up to #41.
=> Only emit inline-assembly when building for AVR

Makefile
The previous sed expression would remove arbitrary lines which can break easily.  Instead, only remove actual extern crate lines.
This will provide a seamless upgrade to the next svd2rust version which contains commit 85615cb0bbc8 ("Use and generate code for Edition 2018 only ") and thus no longer emits 'extern crate' lines.
=> make: Properly remove 'extern crate' lines

CHANGELOG.md, patch/atmega1280.yaml, patch/atmega168.yaml, patch/atmega2560.yaml, patch/atmega328p.yaml, patch/atmega32u4.yaml, patch/atmega64.yaml, patch/atmega8.yaml, patch/attiny85.yaml, patch/attiny88.yaml, patch/common/port.yaml
> Writing a logic one to PINxn toggles the value of PORTxn, independent on the value of DDRxn. Note that the SBI instruction can be used to toggle one single bit in a port.
=> Make the PINx registers writeable

patch/attiny84.yaml
Haven't found any other variants which are affected by this, but it may be worth pulling all of the access-related patches into common or creating a common/tiny/adc patch.
=> fix: attiny84 ADCSRA should be read-write

patch/timer/dev/16bit.yaml, patch/timer/dev/8bit-async.yaml, patch/timer/dev/8bit.yaml
Update AtmegaX8 Timers TIFR register to Write-Read (used in event driven code for clear overflow and other events without interrupt handler)
=> fix: atmegaX8 TIFR should be read-write

patch/atmega64.yaml, patch/common/spi.yaml
Latest `svd2rust` built from git seems to be more strict on the validity of enumerated values (they must fit into the field they are for now).  This will break some of the current chip descriptions.
Fix all those cases so we are prepared for when `svd2rust` releases a new version.  A few of the changes will be breaking, which means the next version bump of `avr-device` after merging this PR must be a major one.
=> Fix svd2rust regressions

.travis.yml
The latest git version of svd2rust contains some important fixes that we depend on.  Use it instead of the latest version from crates.io.
=> Use latest version of svd2rust in CI

patch/atmega328p.yaml, patch/atmega328pb.yaml
The INT0 and INT1 fields in the EIMSK register were incorrectly
combined into a 2 bit field, split into individual bits
Allowed write access to PRR0 and PRR1 in atmega328pb
=> Split INT field into 2 bits for atmega328 and atmega328pb

patch/atmega1280.yaml, patch/atmega168.yaml, patch/atmega2560.yaml, patch/atmega328p.yaml, patch/atmega328pb.yaml, patch/atmega32u4.yaml, patch/atmega48p.yaml, patch/atmega64.yaml, patch/atmega644.yaml, patch/atmega8.yaml, patch/atmega8u2.yaml, patch/attiny84.yaml, patch/attiny841.yaml, patch/attiny85.yaml, patch/attiny861.yaml, patch/attiny88.yaml, patch/common/ac.yaml, patch/common/adc.yaml, patch/common/port.yaml, patch/common/spi.yaml, patch/common/tiny/exint.yaml, patch/common/tiny/usi.yaml, patch/common/twi.yaml, patch/common/usart.yaml, patch/common/wdt.yaml, patch/timer/dev/16bit-tiny861-tc0.yaml, patch/timer/dev/16bit.yaml, patch/timer/dev/8bit-async.yaml, patch/timer/dev/8bit-tiny85-tc1.yaml, patch/timer/dev/8bit.yaml
Due to a [change in `atdf2svd`][1], all these access mode patches are no longer required - they are now translated correctly from the vendor source file.
Drop all patches which no longer change the output (the code before and after this changeset is equivalent when using the new atdf2svd).
[1]: https://github.com/Rahix/atdf2svd/commit/a189276b3540b647fab832946edf0acf39730a0e
---
=> Drop unnecessary access mode patches

.github/workflows/ci.yml
Fixes anyhow incomatiblity with the old nightly we must use right now.
=> ci: Use stable Rust for building svd2rust

macros/src/lib.rs
This change brings in the cortex-m-rt macro support to identify and convert static mut variables as described in the embedded rust book chapter on [exceptions](https://docs.rust-embedded.org/book/start/exceptions.html).
=> implement cortex-m-rt-macros static mut conversion

.github/workflows/ci.yml, Makefile, README.md, patch/attiny841.yaml
Upgrade our buildscripts, CI, and documentation for svd2rust 0.19.  This upgrade actually surfaced an error in the ATtiny841 patches which I've fixed as well.
=> Upgrades for svd2rust 0.19

Cargo.toml, Makefile, README.md, patch/atmega128rfa1.yaml, patch/common/usart.yaml, src/devices/mod.rs, src/lib.rs, vendor/atmega128rfa1.atdf
Adds basic ATmega128RFA1 support.
This has been partially tested (GPIO, SPI) with changes I've got pending to `avr-hal` libraries, but I don't have a good enough development board to test the other peripherals more than ensuring they build.
This PR also adjusts the common USART patches for `UCSZ?` slightly to work with the ATmega128RFA1's ATDF. The ATDF does specify enum values for the field but the patch was not `_replace_enum`. I've changed the common patch to use `_replace_enum`, to make sure the fields are consistent with other micros.
=> Add ATmega128RFA1 support

Cargo.toml, Makefile, README.md, patch/atmega1284p.yaml, patch/timer/atmega1284p.yaml, src/devices/mod.rs, src/lib.rs, vendor/atmega1284p.atdf
Title says it all :)
I used the atmega328p as inspiration for the SVD patches since it's fairly similar to atmega1284p. I did apply a few more splits for registers in EXINT to make handling interrupts a bit smoother.
=> Add support for ATmega1284p

Cargo.toml, README.md, build.rs, src/asm.rs, src/interrupt.rs, src/lib.rs
Closes https://github.com/Rahix/avr-device/issues/91.
Starting from 1.59.0, rustc has been removed support for the `llvm_asm!()` macro, making it impossible to use `avr-device` with newer compilers.
This merge requests adjusts the code, so that it continues to use `llvm_asm!()` on older compilers (such as the infamous `nightly-2021-01-07`), but switches to `asm!()` on the newer ones.
I've checked the code on `nightly-2021-01-07` and a custom-built `rustc` from around yesterday (`b759b2218649016cc40e82bdd6d958e2277ff6d7`), and everything seems to be working correctly.
I've compared the generated LLVM IRs for an application I'm developing, and they are virtually identical:
`enable()`:
```
older rustc:
tail call addrspace(0) void asm sideeffect "sei", ""() #10, !srcloc !5
newer rustc:
tail …
```
=> Add support for `asm!()`

patch/atmega1280.yaml, patch/atmega2560.yaml, patch/timer/atmega1280-2560.yaml
It seems like the timer patch for the atmega2560 is applicable for the atmega1280 as well, unless I'm mistaken.
I stumbled over the lack of timer patches for the atmega1280 while working on https://github.com/Rahix/avr-hal/pull/272 , this PR should fix this by using the same patch for the 1280 as for the 2560.
As far as I can tell the only difference between the two MCU's seems to be the amount of flash memory available(?).
=> Use the same timer patch for atmega1280 as for atmega2560

patch/attiny167.yaml, patch/timer/attiny167.yaml, patch/timer/dev/8bit-tiny167.yaml
Adds patches for TC0 and TC1 on the attiny167 so that prescaler values (and the `COMnx` register values) can be set by human readable methods (`.prescale_64()` instead of `.val_0x03()` for example).
=> Adds patches for the timers on attiny167

Cargo.toml, src/interrupt.rs
Avoid unnecessary mask and branch instructions.
The basic reasoning behind this is that all other flags in the `SREG` can be clobbered without ill effects. The `restore()` function is an optimization fence and the compiler is not allowed to make assumptions about memory or `SREG` state after execution.
This avoids an `and` and a `breq` instruction or similar in every critical section.
This is an API breakage that requires an incompatible version bump.
Question: Should we return a struct instead of u8? That would give us the opportunity to change semantics without breaking API in the future.
I hope I got the `llvm_asm!` part of `restore()` right. I didn't test it. What about removing all `llvm_asm!`?
=> irq: Optimize interrupt save/restore

README.md, macros/Cargo.toml, src/interrupt.rs, src/lib.rs
Some minor fixes, that slipped through before release.
* Mutex::borrow() cs parameter is not a reference (in new bare-metal).
* Mutex example: Use proper code in a function body that would actually compile.
* Document the `ufmt` feature.
* Cargo example version
Shall we also bump the macros edition to 2021?
=> Small documentation fixes

patch/atmega8.yaml, patch/timer/atmega8.yaml, patch/timer/dev/16bit-mega8.yaml, patch/timer/dev/8bit-async-mega8.yaml, patch/timer/dev/8bit-mega8.yaml, vendor/atmega8.atdf
This PR adds patches for ATmega8 needed to implement ATMega8 to avr-hal easily.
Unfortunately I had to edit the vendor file, because there is a field WGM2 consisting of WGM21 and WGM20 that are not directly next to each other. Any idea on how to patch this correctly?
=> Add patches for ATmega8

Cargo.toml, src/interrupt.rs
Due to the changed design of the `critical-section` crate, we now have to provide an implementation over here.
Add a `critical-section-impl` feature flag which can be used to enable the implementation.
=> Add implementation for critical-section

src/asm.rs
This is a counterpart to `cortex_m::asm::delay` but for AVR.
It is intended for very simple delays in low-level drivers that don't require precision or real-time accuracy.
In those situations, it provides these benefits over the alternatives:
- Compared to `Delay` from avr-hal, this dependency is more convenient; Sometimes it is not desired or not even possible to depend on avr-hal, and also the driver does not need to know the CPU clock frequency (if it doesn't care about 16x longer delays at 1MHz vs 16MHz).
- Compared to using hardware timers, this doesn't require ownership of any system resources, leaving more for the end user.
=> Add asm::delay_cycles

patch/attiny828.yaml
Hey!
Am currently working on a PR to add ATtiny828 to `avr-hal`. Just found out that I previously used a wrong name for an ADC ref voltage variant.
My bad, sorry for the inconvenience.
=> ATtiny828: Fix ADC reference voltage variant name

patch/attiny85.yaml
Fix https://github.com/Rahix/avr-device/issues/130 by adding fields for pins where the pin change interrupt can be enabled. I.e. it is possible to use this
``` rust
self.exint.pcmsk.modify(|_, w| w.pcint0().set_bit());
```
instead of this:
``` rust 
self.exint.pcmsk.modify(|_, w| w.bits(1));
```
Since the two most significant bits of PCMSK on the attiny85 are reserved, it would make sense to change the write constraint to `[0, 63]`, but I failed to achieve this. the code is commented in commit https://github.com/Rahix/avr-device/commit/78b331fd41c9228ba10e3354f5c7d1482eae47e0 . Because of this, the PR is still a draft.
=> Patch attiny85 PCMSK register

patch/attiny2313-common.yaml
Usually, atdf2svd generates fields for each pin in the DDR,PORT,PIN registers based on additional information in the ATDF file.  However, it seems for the ATtiny2313{,A} chips, this information is missing.  Patch in the missing fields manually.
This was found via https://github.com/Rahix/avr-hal/pull/500.
=> attiny2313{,a}: Add missing pin fields

patch/atmega32u4.yaml
For some reason, the ATDF file does not show the PF7 pin.  But as this pin does exist for the MCU, use a patch to add it.
Diff:
```diff
diff --color -Nur svd-orig/atmega32u4.svd.patched svd/atmega32u4.svd.patched
--- svd-orig/atmega32u4.svd.patched	2024-01-28 20:05:48.682604785 +0100
+++ svd/atmega32u4.svd.patched	2024-01-28 20:05:53.675998585 +0100
@@ -3040,7 +3040,8 @@
<bitRange>[6:6]</bitRange>
<access>read-write</access>
</field>
-          </fields>
+          <field><name>PF7</name><description>Pin F7</description><bitRange>[7:7]</bitRange><access>read-write</access></field>
+            </fields>
</register>
<register>
<name>PINF</name>
@@ -3079,7 +3080,8 @@
<bitRange>[6:6]</bitRange>
<access>read-write</access>
</field>
-          </fields>
+ …
```
=> atmega32u4: Add missing pin PF7

Cargo.toml, Makefile, README.md, patch/avr64du28.yaml, patch/avr64du32.yaml, src/devices/mod.rs, src/lib.rs, vendor/avr64du28.atdf, vendor/avr64du32.atdf
Adds basic support for AVR64DU32 and AVR64DU28. I have only spot checked the generated doc, they look ok.
https://www.microchip.com/en-us/product/AVR64DU32
=> Add support for new AVR USB devices. AVR64DU32 and AVR64DU28.

.github/workflows/ci.yml, README.md
Due to a [regression caused by proc-macro2][1], we have to use a locked version of svd2rust to successfully build the code in this crate.
[1]: rust-embedded/svd2rust#863
=> Use locked svd2rust

.github/workflows/ci.yml, README.md
The new version includes https://github.com/Rahix/atdf2svd/pull/67.
=> Update to atdf2svd version 0.5.0

patch/attiny202.yaml, patch/attiny212.yaml, patch/attiny214.yaml, patch/attiny402.yaml, patch/attiny404.yaml, patch/attiny412.yaml, patch/attiny414.yaml, patch/attiny416.yaml, patch/common/attiny-xmega/0-series.yaml, patch/common/attiny-xmega/1-series.yaml, patch/common/attiny-xmega/common.yaml
A light refactor of the patch files. Since the ATtiny xmega series have a lot in common, it makes more sense to structure their patch files as "common + 0 series" or "common + 1 series" than "0 series" or "0 series + 1 series"
=> Refactored attiny-xmega patch files

patch/common/attiny-xmega/common.yaml
This uses the same convention as SPI `FOSC*` in `patch/common/spi.yaml`
=> Rewrite prescaler enum in ATtiny xmega SPI*.CTRLA

patch/atmega128rfa1.yaml, patch/timer/atmega128rfa1.yaml
In `timer/atmega128rfa1.yaml` "_replace_enum" from `timer/dev/*.yaml` applies only for first COM* definition (svdtools 0.1.27) so I added it manually. I don't know what the reason but patch works correctly without manual definitions with svdtools 0.3.20 installed from cargo.
=> Update some peripherals for Atmega128rfa1

.github/workflows/ci.yml, Makefile, README.md, gen-intr-lut.sh, patch/atmega8.yaml, patch/attiny13a.yaml, patch/attiny85.yaml, patch/common/ac.yaml, patch/common/attiny-xmega/common.yaml, patch/common/mega0/port.yaml, patch/common/tiny/exint.yaml, patch/common/twi.yaml
This change removes a dependency on python/pip and is more consistent with the installation of the other supporting tools.
=> svdtools: install rust version

build.rs
Change the context messages for errors so they are more in line with the way `anyhow` intends context messages to be used.  This means the message will read properly top-down and users will hopefully be less confused when trying to understand what went wrong.
Cc: @LuigiPiucco
=> build: Update error messages

build.rs
Fix #187.
Since I had some extra time, I went ahead and took care of this. It's a simple change, I merged `InputFinder::filter_from_features` and `InputFinder::find`. We still iterate every path, to add the name to the list of available MCUs in case of error, but the inputs are only inserted if the variable is present.
=> build: only parse selected MCU inputs

.github/workflows/ci.yml, examples/atmega328p/rust-toolchain.toml
See [1] for details.
Some floating point intrinsics were added in this newer version which helps on systems where these intrinsics are not provided by avr-gcc.
[1]: https://github.com/Rahix/avr-hal/pull/651
=> Upgrade rust toolchain

build.rs
Just two minor improvements I made while playing with the build-script code a bit.
Cc: @LuigiPiucco 
Ref: #157
=> Minor build-script improvements

Cargo.toml, examples/atmega328p/Cargo.toml, src/interrupt.rs
The new svd2rust code needs `critical-section` for implementing the `Peripherals::take()` function.  This means almost all uses of `avr-device` will need it as well.
Rename the `critical-section-impl` feature to just `critical-section` and make it a part of the crate's default features.
Cc: @LuigiPiucco @tones111 
Ref: #157
=> Enable critical-section by default

src/asm.rs
Fix #175.
The check with `u8::MAX` is there because some MCUs (the really small ones whose data space address fits in a `u8`) may not have `SPH`. Because `extern static`s are not as optimizable as `const`s, the resulting binary can't eliminate the opposing branch, something that could be worked on.
=> asm: Add function to get stack size

Cargo.toml, src/devices.rs, src/lib.rs, vendor/avr128db28.atdf
Adds AVR128DB28
Note that the README currently has an "AtMega USB" column with two AVR64DU devices, which could be moved (or duplicated) to an AVR (Modern) column I added which now only contains AVR128DB28.
I checked the documentation and genererated code,  and I did not see the need for any yaml patch files (the AVR64DU devices also have none), but I might be missing something.
=> Add AVR128DB28 device
